---

- name: Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items: ["python-psycopg2", "python-pycurl"]

- name: Add PostgreSQL repository apt-key
  register: _repo_key
  apt_key:
    id: ACCC4CF8
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: Add PostgreSQL repository
  register: _repo
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
    state: present

- name: Update apt cache
  when: _repo_key.changed or _repo.changed
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: "{{item}}"
    state: present
  environment: postgresql_env
  with_items:
    - libpq-dev
    - postgresql-common
    - "postgresql-client-{{postgresql_version}}"
